version: '3.12.3'
services:
        web:
                image: flask_2025
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "3168:3168"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
