services:
        web:
                image: tower-defense
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "3168:3168"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
